name: Run Production Prisma Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'prisma/migrations/**/*'

jobs:
  main_migrations:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Set the required variables
          repo_owner="AmbossTech"
          repo_name="amboss-banco-ci"
          event_type="trigger-workflow"

          gh workflow -R $repo_owner/$repo_name -r main run banco-server-prod-migrations.yaml
